ifneq ($(CONFIG_NEST_FIXTURE),y)
obj-y += lib/
endif
obj-$(CONFIG_NEST_MT92) += mt92.o
obj-$(CONFIG_NEST_MT22P1) += mt221.o
obj-$(CONFIG_NEST_MT22P1_OLD) += mt221.o
obj-$(CONFIG_NEST_MT60) += mt60.o
obj-$(CONFIG_NEST_MT60_OLD) += mt60.o
obj-$(CONFIG_NEST_MT80_OLD) += mt80.o
obj-$(CONFIG_NEST_HCU_GAC) += hcu.o
obj-$(CONFIG_NEST_IGBT_BURN) += burn.o
obj-$(CONFIG_NEST_TESTFIXTURE) += testfixture.o
obj-$(CONFIG_NEST_FIXTURE) += fixture.o
