obj-$(CONFIG_STM32F10X_LD) += startup_stm32f10x_ld.o
obj-$(CONFIG_STM32F10X_MD) += startup_stm32f10x_md.o
obj-$(CONFIG_STM32F10X_HD) += startup_stm32f10x_hd.o
obj-$(CONFIG_STM32F10X_CL) += startup_stm32f10x_cl.o