/* Autogenerated by make, please do not edit me manually
   date: 2013/01/02 19:50:33
*/
#ifndef __7060LIBS_H_
#define __7060LIBS_H_

#include "LibIAR/Adc/LibADC706x.h"
#include "LibIAR/Clk/LibClk706x.h"
#include "LibIAR/Dac/LibDAC706x.h"
#include "LibIAR/Fee/LibFee706x.h"
#include "LibIAR/T/LibTim706x.h"
//#include "LibIAR/Urt/LibUrt706x.h"

#endif /*__7060LIBS_H_*/
