/* Autogenerated by make, please do not edit me manually
   date: 2013/01/02 16:58:59
*/
#ifndef __ADUC706X_H_
#define __ADUC706X_H_

#include "LibIAR/Adc/LibADC706x.h"
#include "LibIAR/Clk/LibClk706x.h"
#include "LibIAR/Dac/LibDAC706x.h"
#include "LibIAR/Fee/LibFee706x.h"
#include "LibIAR/T/LibTim706x.h"
#include "LibIAR/Urt/LibUrt706x.h"

#endif /*__ADUC706X_H_*/
