obj-y += sys/
obj-$(CONFIG_TOOLCHAIN_GCC) += gcc/
obj-$(CONFIG_TOOLCHAIN_IAR) += iar/
obj-$(CONFIG_TASK_SHELL) += shell/
obj-$(CONFIG_TASK_OSD) += osd/
obj-$(CONFIG_TASK_GUI) += gui/
obj-$(CONFIG_LIB_LWIP) += lwip/
obj-$(CONFIG_LIB_FATFS) += fatfs/
obj-$(CONFIG_LIB_COMMON) += common/
obj-$(CONFIG_LIB_FREERTOS) += FreeRTOS/
obj-$(CONFIG_LIB_UDISK) += mass_storage/
obj-$(CONFIG_LIB_PRIV) += priv/
obj-$(CONFIG_LIB_LUA) += lua/
obj-$(CONFIG_LIB_ZBAR) += zbar/
obj-$(CONFIG_LIB_INSTR) += instr/
obj-$(CONFIG_LIB_PMSM) += pmsm/

inc-$(CONFIG_LIB_FATFS) += fatfs/
