obj-y += sys/
obj-$(CONFIG_TOOLCHAIN_GCC) += gcc/
obj-$(CONFIG_TOOLCHAIN_IAR) += iar/
obj-$(CONFIG_TASK_MOTOR) += motor/
obj-$(CONFIG_TASK_VVT) += vvt/
obj-$(CONFIG_TASK_SHELL) += shell/
obj-$(CONFIG_TASK_STEPMOTOR) += sm/
obj-$(CONFIG_TASK_OSD) += osd/
