obj-y += sys/
obj-$(CONFIG_TOOLCHAIN_GCC) += gcc/
obj-$(CONFIG_TOOLCHAIN_IAR) += iar/
obj-$(CONFIG_TASK_SHELL) += shell/
obj-$(CONFIG_TASK_OSD) += osd/
obj-$(CONFIG_LIB_LWIP) += lwip/
obj-$(CONFIG_LIB_FATFS) += fatfs/
