obj-y += cmsis/
obj-$(CONFIG_USE_STDPERIPH_DRIVER)	+= StdPeriph/
obj-$(CONFIG_USE_STDETHERNET_DRIVER)	+= STM32_ETH_Driver/
obj-$(CONFIG_USE_STM32_USB_DRIVER)	+= STM32_USB_Driver/

inc-y += cmsis/
inc-$(CONFIG_USE_STDPERIPH_DRIVER)	+= StdPeriph/inc/
inc-$(CONFIG_USE_STDETHERNET_DRIVER)	+= STM32_ETH_Driver/inc/
inc-$(CONFIG_USE_STM32_USB_DRIVER)	+= STM32_USB_Driver/inc/

icf-y += stm32f103rb.icf
