obj-$(CONFIG_USE_STDPERIPH_DRIVER)	+= cmsis/
obj-$(CONFIG_USE_STDPERIPH_DRIVER)	+= StdPeriph/
obj-$(CONFIG_USE_STDETHERNET_DRIVER)	+= STM32_ETH_Driver/
obj-$(CONFIG_USE_STM32_USB_DRIVER)	+= STM32_USB_Driver/

inc-$(CONFIG_USE_STDPERIPH_DRIVER)	+= cmsis/
inc-$(CONFIG_USE_STDPERIPH_DRIVER)	+= StdPeriph/inc/
inc-$(CONFIG_USE_STDETHERNET_DRIVER)	+= STM32_ETH_Driver/inc/
inc-$(CONFIG_USE_STM32_USB_DRIVER)	+= STM32_USB_Driver/inc/

#v3.5 st lib support
obj-$(CONFIG_USE_STDPERIPH_V35)		+= cmsis_3.5/
obj-$(CONFIG_USE_STDPERIPH_V35)		+= StdPeriph_3.5/
inc-$(CONFIG_USE_STDPERIPH_V35)		+= cmsis_3.5/
inc-$(CONFIG_USE_STDPERIPH_V35)		+= StdPeriph_3.5/inc/

icf-y += stm32f103rb.icf
