obj-y += cmd.o
obj-y += shell.o
obj-$(CONFIG_SHELL_FATFS) += cmd_fatfs.o
obj-$(CONFIG_SHELL_MOTOR) += cmd_motor.o
obj-$(CONFIG_SHELL_MOTOR_DEBUG) += cmd_debug.o
obj-$(CONFIG_SHELL_VVT) += cmd_vvt.o
obj-$(CONFIG_SHELL_FLASH_STM32) += cmd_flash.o
obj-$(CONFIG_SHELL_LOAD) += cmd_load.o
