TOP_DIR ?= $(shell pwd)
IAR_TOOL = $(TOP_DIR)/scripts/iar.py
IAR_FILE = $(TOP_DIR)/projects/bldc/bldc.ewp
M ?= src/

-include $(TOP_DIR)/.config
-include $(M)Makefile

#create iar project file according to the result of 'make xconfig'
iar: iar_clr iar_inc iar_add

iar_clr:
	$(IAR_TOOL) clr $(IAR_FILE)
iar_inc:
	$(IAR_TOOL) inc $(IAR_FILE) src/include/
	$(IAR_TOOL) inc $(IAR_FILE) src/cpu/stm32/cmsis/
	$(IAR_TOOL) inc $(IAR_FILE) src/cpu/stm32/StdPeriph/inc/
iar_add:
	@echo target=$@ M=$(M): obj-y = $(obj-y)
	@$(IAR_TOOL) add $(IAR_FILE) $(M) $(obj-y)
	@for dir in $(obj-y); do\
		if [ -d $(M)$$dir ];\
		then \
			make -s -C $(TOP_DIR) M=$(M)$$dir $@; \
		fi \
	done

#config
AUTOCONFIG_HEAD_FILE = $(TOP_DIR)/src/include/autoconfig.h
AUTOCONFIG_FILE = $(TOP_DIR)/.config

board_config:
	@if [ -z $(wildcard $(AUTOCONFIG_HEAD_FILE)) ];\
	then \
		echo "System not configured!!!"; \
		echo "Please try: ";\
		echo "  make your_board_name_config"; \
		echo "  make"; \
		echo ""; \
		exit 1; \
	fi
	
hurry_config: board_unconfig
	@echo -e "/*autogenerated, do not edit!!*/\r" > $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_TOOLCHAIN_IAR 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_STM32F10X_MD 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_USE_STDPERIPH_DRIVER 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_HSE_VALUE    12000000\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_TASK_MOTOR 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_TASK_SHELL 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_DRIVER_CONSOLE 1\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_SYSTEM_DEBUG 0\r" >> $(AUTOCONFIG_HEAD_FILE)
	@echo -e "#define CONFIG_MOTOR_DEBUG 0\r" >> $(AUTOCONFIG_HEAD_FILE)
	
	@echo -e "#autogenerated, do not edit!!\r" > $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_TOOLCHAIN_IAR=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_STM32F10X_MD=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_USE_STDPERIPH_DRIVER=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_HSE_VALUE=12000000\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_TASK_MOTOR=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_TASK_SHELL=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_DRIVER_CONSOLE=y\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_SYSTEM_DEBUG=n\r" >> $(AUTOCONFIG_FILE)
	@echo -e "CONFIG_MOTOR_DEBUG=n\r" >> $(AUTOCONFIG_FILE)

board_unconfig:
	@rm -rf $(AUTOCONFIG_HEAD_FILE)
	
clean:
	@rm -rf $(TOP_DIR)/projects/bldc/Debug
	@rm -rf $(TOP_DIR)/projects/bldc/Release
	@rm -rf $(TOP_DIR)/projects/bldc/settings
	@rm -rf $(TOP_DIR)/projects/bldc/bldc.dep
	@rm -rf $(TOP_DIR)/projects/bldc/bldc.ewd

distclean: clean iar_clr
	@rm -rf $(AUTOCONFIG_FILE)
	@rm -rf $(AUTOCONFIG_HEAD_FILE)