obj-y += gui.o
obj-y += gui_lcd.o
obj-y += gui_event.o
obj-y += gui_window.o
obj-y += gui_widget.o
obj-y += gui_widget_fixed.o
obj-y += gui_widget_button.o

obj-$(CONFIG_GUI_DEMO) += gui_demo.o
bin-$(CONFIG_GUI_DEMO) += gui_demo.bmp.bin
bin-$(CONFIG_OID_MAIN) += gui_demo.bmp.bin
