function img(fname)
%this program is used to convert image to c array

image = imread(fname);
array = image';

[rows, cols] = size(image);
len = rows * cols;

N = len; %bytes
I = 8; %bytes per line to display

%disp head
str = sprintf('* ori from: %s', fname);
disp('/*****************************************************');
disp('* image file generated by img.m v1.0');
disp(str);
disp('* copyright (c) miaofng@2011');
disp('******************************************************/');

str = sprintf('#define IMAGE_W %d', cols);
disp(str)
str = sprintf('#define IMAGE_H %d', rows);
disp(str)

str = sprintf('const char image[] = {');
disp(str)

for n = 1:N
	val = array(n);
	left = mod(n, I);
	if left == 1 %first element
		str = sprintf('	0x%02x,', val);
		note = sprintf(' /*row %03d, col %03d*/', (n-mod(n, cols))/cols, mod(n, cols) - 1);
    elseif ((left == 0) | (n == N)) %last element
		dat = sprintf(' 0x%02x,', val);
		str = [str, dat];
		str = [str, note];
		disp(str);
		
	else
		dat = sprintf(' 0x%02x,', val);
		str = [str, dat];
	end
end
disp('};');