obj-$(CONFIG_YREP_V1P0) += ybs_repeater.o
obj-$(CONFIG_YREP_V1P0) += ybs_sensor.o
obj-$(CONFIG_YREP_V1P0) += ybs_bsp.o
obj-$(CONFIG_YREP_V1P0) += ybs_dc.o
obj-$(CONFIG_YREP_V1P0) += ybs_lwip.o
obj-$(CONFIG_YREP_V1P0) += ybs_dsp.o
