obj-$(CONFIG_CPU_CMSIS) += cmsis/
obj-$(CONFIG_CPU_STM32)				+= stm32/
obj-$(CONFIG_CPU_LM3S)				+= lm3s/
obj-$(CONFIG_CPU_SAM3U)				+= sam3u/
obj-$(CONFIG_CPU_LPC178X)			+= lpc178x/

inc-$(CONFIG_CPU_CMSIS) += cmsis/
inc-$(CONFIG_CPU_STM32)				+= stm32/
inc-$(CONFIG_CPU_LM3S)				+= lm3s/
inc-$(CONFIG_CPU_SAM3U)				+= sam3u/
inc-$(CONFIG_CPU_LPC178X)			+= lpc178x/
