obj-y += cmsis/
obj-$(CONFIG_CPU_STM32)				+= stm32/
obj-$(CONFIG_CPU_LM3S)				+= lm3s/
obj-$(CONFIG_CPU_SAM3U)				+= sam3u/

inc-y += cmsis/
inc-$(CONFIG_CPU_STM32)				+= stm32/
inc-$(CONFIG_CPU_LM3S)				+= lm3s/
inc-$(CONFIG_CPU_SAM3U)				+= sam3u/
