ifeq ($(CONFIG_DRIVER_LCD),y)
	obj-y += lcd.o
	obj-$(CONFIG_LCD_CMD) += lcd_cmd.o
	obj-$(CONFIG_LCD_1602) += lcd1602.o
	obj-$(CONFIG_LCD_JHD204A) += jhd204a.o
	obj-$(CONFIG_LCD_ILI932X) += ili9320.o
	obj-$(CONFIG_LCD_S6B33) += s6b33.o
	obj-$(CONFIG_LCD_ILI9161) += ili9161.o
	obj-$(CONFIG_LCD_SSD1289) += ssd1289.o
	obj-$(CONFIG_CUSTOM_DISPLAY) += cd.o
endif
