obj-$(CONFIG_TASK_APTC131) += apt_dlg.o
obj-$(CONFIG_TASK_APTC131) += c131.o
obj-$(CONFIG_TASK_APTC131) += c131_driver.o
obj-$(CONFIG_TASK_APTC131) += c131_diag.o
obj-$(CONFIG_TASK_APTC131) += apt_cmd.o
