#sss ctrl card
obj-$(CONFIG_SSS_CARD_CTRL) += sss.o

#sss Side Impact Sensor card
obj-$(CONFIG_SSS_CARD_SIS) += sis.o
obj-$(CONFIG_SSS_CARD_SIS) += dbs.o
obj-$(CONFIG_SSS_CARD_SIS) += sis_card.o
obj-$(CONFIG_SSS_CARD_SIS) += psi5.o
