#sss ctrl card
obj-$(CONFIG_SSS_CARD_CTRL) += sss.o

#sss Side Impact Sensor card
obj-$(CONFIG_SSS_CARD_SIS) += drivers/
obj-$(CONFIG_SSS_CARD_SIS) += sss_can.o
obj-$(CONFIG_SSS_CARD_SIS) += sss_card.o
obj-$(CONFIG_SSS_CARD_SIS) += sis_code.o
obj-$(CONFIG_SSS_CARD_SIS) += sis_decode.o
obj-$(CONFIG_SSS_CARD_SIS) += sis.o


