obj-$(CONFIG_DRIVER_MAC) += ethernetif.o
obj-$(CONFIG_MAC_STM32) += stm32_mac.o
obj-$(CONFIG_MAC_LM3S) += stellarisif.o
obj-$(CONFIG_MAC_ENC424J600) += enc_mac.o
obj-$(CONFIG_MAC_ENC28J60) += enc_mac.o
obj-$(CONFIG_MAC_LPC178X) += lpc178x_mac.o
