ifeq ($(CONFIG_CPU_STM32),y)
	obj-$(CONFIG_DRIVER_COUNTER1) += counter1_stm32.o
	obj-$(CONFIG_DRIVER_COUNTER2) += counter2_stm32.o
	obj-$(CONFIG_DRIVER_COUNTER3) += counter3_stm32.o
	obj-$(CONFIG_DRIVER_COUNTER4) += counter4_stm32.o
endif
obj-$(CONFIG_DRIVER_COUNTER_CMD) += counter_cmd.o
