obj-$(CONFIG_MISC_VHD) += lt-1105-0106.o
obj-$(CONFIG_MISC_SLU) += lte-1107-0017.o
obj-$(CONFIG_MISC_SPC) += lte-1107-0021.o
obj-$(CONFIG_MISC_BPTEST) += bptest.o
obj-$(CONFIG_MISC_ICT) += lte-1202-0046.o
