ifeq ($(CONFIG_CPU_STM32),y)
	obj-$(CONFIG_DRIVER_PWMIN1) += pwmin1_stm32.o
	obj-$(CONFIG_DRIVER_PWMIN2) += pwmin2_stm32.o
	obj-$(CONFIG_DRIVER_PWMIN3) += pwmin3_stm32.o
	obj-$(CONFIG_DRIVER_PWMIN4) += pwmin4_stm32.o
endif
	obj-$(CONFIG_DRIVER_PWMIN_CMD) += pwmin_cmd.o
