obj-y += cmsis/
inc-y += cmsis/
icf-$(CONFIG_ICF_RAM) += cmsis/linker/ldscript_iram_iar.icf
icf-$(CONFIG_ICF_ROM) += cmsis/linker/ldscript_irom_iar.icf

obj-$(CONFIG_USE_LPC_DRIVER)	+= Drivers/
