/* Autogenerated by make, please do not edit me manually
   date: 2013/01/02 18:44:54
*/
#ifndef __ADUC706X_H_
#define __ADUC706X_H_

#include "config.h"

#ifdef CONFIG_ADUC706X_ADILIB
#include "7060Libs.h"
#endif

#include <intrinsics.h>
#include <AnalogDevices/ioaduc7060.h>
#include "system_aduc706x.h"
#include "aduc706x_it.h"

#endif /*__ADUC706X_H_*/
