obj-$(CONFIG_DRIVER_KEYBOARD) += key.o
obj-$(CONFIG_DRIVER_RCKEY) += key_rc.o
obj-$(CONFIG_DRIVER_ADCKEY) += key_adc.o
obj-$(CONFIG_DRIVER_GPIOKEY) += key_gpio.o
obj-$(CONFIG_DRIVER_ENCODER) += key_encoder.o
obj-$(CONFIG_DRIVER_ENCODER) += encoder/