#ECU
obj-$(CONFIG_PDI_ECU) += pdi.o
obj-$(CONFIG_PDI_ECU) += drv.o
obj-$(CONFIG_PDI_SDM10) += sdm10.o
obj-$(CONFIG_PDI_DM) += dm_dma.o
obj-$(CONFIG_PDI_RC) += rc_n7.o
obj-$(CONFIG_PDI_B515) += B515.o
obj-$(CONFIG_PDI_J04N) += J04N.o
obj-$(CONFIG_PDI_SDM30) += sdm30.o
obj-$(CONFIG_PDI_M16) += M16.o
obj-$(CONFIG_PDI_RP) += RP.o
obj-$(CONFIG_PDI_RP) += CMF1.o
obj-$(CONFIG_PDI_AP2) += AP2.o
obj-$(CONFIG_PDI_BA) += BA.o
obj-$(CONFIG_PDI_BANEW) += BA_NEW.o
obj-$(CONFIG_PDI_CCP2) += CCP2.o
obj-$(CONFIG_PDI_B12L) += B12L.o
obj-$(CONFIG_PDI_B515RSU) += B515RSU.o
obj-$(CONFIG_PDI_B562) += B562.o
obj-$(CONFIG_PDI_RCLE) += RCLE.o
obj-$(CONFIG_PDI_CHB041) += CHB041.o
obj-$(CONFIG_PDI_HZH) += HZH.o
obj-$(CONFIG_PDI_TL_NEW) += TL_NEW.o

#RSU4
inc-$(CONFIG_PDI_RSU4) += rsu4/
obj-$(CONFIG_PDI_RSU4) += rsu4/bsp.o
obj-$(CONFIG_PDI_RSU4) += rsu4/pdi.o
obj-$(CONFIG_PDI_RSU4) += ecu/ecu.o
obj-$(CONFIG_RSU_P71A) += rsu4/p71a.o
obj-$(CONFIG_RSU_KP108) += rsu4/kp108.o
obj-$(CONFIG_RSU_VOLVO) += rsu4/volvo.o
obj-$(CONFIG_RSU_DFL322) += rsu4/dfl322.o
