obj-y += pdi.o
obj-y += cfg.o
obj-y += drv.o
obj-$(CONFIG_PDI_SDM10) += sdm10.o
obj-$(CONFIG_PDI_DM) += dm_dma.o
obj-$(CONFIG_PDI_RC) += rc_n7.o
obj-$(CONFIG_PDI_B515) += B515.o
obj-$(CONFIG_PDI_B515) += J04N.o
