obj-$(CONFIG_TASK_MOTOR) += bldc/
obj-$(CONFIG_TASK_VVT) += vvt/
obj-$(CONFIG_TASK_STEPMOTOR) += sm/
obj-$(CONFIG_TASK_ETHDEMO) += eth_demo/
obj-$(CONFIG_TASK_HVP) += hvp/
obj-$(CONFIG_TASK_NEST) += nest/
obj-$(CONFIG_TASK_SSS) += sss/

