ifeq ($(CONFIG_CPU_STM32),y)
	obj-$(CONFIG_DRIVER_PWM1) += pwm1_stm32.o
	obj-$(CONFIG_DRIVER_PWM2) += pwm2_stm32.o
	obj-$(CONFIG_DRIVER_PWM3) += pwm3_stm32.o
	obj-$(CONFIG_DRIVER_PWM4) += pwm4_stm32.o
endif
	obj-$(CONFIG_DRIVER_PWM_CMD) += pwm_cmd.o
