obj-y += src/
obj-$(CONFIG_LIB_LWIP) += lwip_lib.o
obj-$(CONFIG_LWIP_APP_HELLO) += lwip_app_hello.o
obj-$(CONFIG_LWIP_APP_TCPSERVER) += lwip_app_tcpserver.o

inc-y += src/include/
inc-y += src/include/ipv4/
inc-y += port/
