obj-$(CONFIG_LWIP_V131) += lwip-1.3.1/
obj-$(CONFIG_LWIP_GIT) += lwip/

obj-$(CONFIG_LIB_LWIP) += lwip_lib.o
obj-$(CONFIG_LWIP_APP_HELLO) += lwip_app_hello.o
obj-$(CONFIG_LWIP_APP_TCPSERVER) += lwip_app_tcpserver.o
obj-$(CONFIG_LWIP_APP_HTTPD) += lwip-contrib/apps/httpserver_raw/
