obj-$(CONFIG_COMMON_PRINT) += print.o
obj-$(CONFIG_COMMON_INIFILE) += inifile.o
obj-$(CONFIG_COMMON_KWP) += kwp.o
obj-$(CONFIG_COMMON_PTP) += ptp.o
obj-$(CONFIG_COMMON_KERMIT) += kermit.o

#linux
obj-y += sort.o
obj-y += circbuf.o
obj-y += crc16.o
obj-y += crc32.o
obj-y += posix_crc.o
obj-y += mempool.o
