obj-$(CONFIG_COMMON_PRINT) += print.o
obj-$(CONFIG_COMMON_INIFILE) += inifile.o
obj-$(CONFIG_COMMON_KWP) += kwp.o
obj-$(CONFIG_COMMON_PTP) += ptp.o
obj-$(CONFIG_COMMON_KERMIT) += kermit.o

#linux
obj-$(CONFIG_COMMON_SORT) += sort.o
obj-y += circbuf.o
obj-$(CONFIG_COMMON_CRC16) += crc16.o
obj-$(CONFIG_COMMON_CRC32) += crc32.o
obj-$(CONFIG_COMMON_CRC_POSIX) += posix_crc.o
obj-$(CONFIG_COMMON_MEMPOOL) += mempool.o
obj-$(CONFIG_COMMON_PID) += pid.o

obj-y += debounce.o
obj-$(CONFIG_COMMON_VCHIP) += vchip.o
obj-$(CONFIG_COMMON_TSTEP) += tstep.o
obj-$(CONFIG_COMMON_POLYFIT) += polyfit.o

obj-$(CONFIG_COMMON_MODBUS) += mb.o
obj-$(CONFIG_COMMON_MODBUS) += mbcrc.o

obj-y += ulp_error.o
obj-y += ulib.o
