LUA_VERSION = 5.1.4
LUA_FOLDER = lua-$(LUA_VERSION)/src

#lua core
obj-y += $(LUA_FOLDER)/lapi.o
obj-y += $(LUA_FOLDER)/lcode.o
obj-y += $(LUA_FOLDER)/ldebug.o
obj-y += $(LUA_FOLDER)/ldo.o
obj-y += $(LUA_FOLDER)/ldump.o
obj-y += $(LUA_FOLDER)/lfunc.o
obj-y += $(LUA_FOLDER)/lgc.o
obj-y += $(LUA_FOLDER)/llex.o
obj-y += $(LUA_FOLDER)/lmem.o
obj-y += $(LUA_FOLDER)/lobject.o
obj-y += $(LUA_FOLDER)/lopcodes.o
obj-y += $(LUA_FOLDER)/lparser.o
obj-y += $(LUA_FOLDER)/lstate.o
obj-y += $(LUA_FOLDER)/lstring.o
obj-y += $(LUA_FOLDER)/ltable.o
obj-y += $(LUA_FOLDER)/ltm.o
obj-y += $(LUA_FOLDER)/lundump.o
obj-y += $(LUA_FOLDER)/lvm.o
obj-y += $(LUA_FOLDER)/lzio.o

#lua lib
obj-y += $(LUA_FOLDER)/lauxlib.o
obj-y += $(LUA_FOLDER)/lbaselib.o
obj-y += $(LUA_FOLDER)/ldblib.o
obj-y += $(LUA_FOLDER)/liolib.o
obj-y += $(LUA_FOLDER)/lmathlib.o
obj-y += $(LUA_FOLDER)/loslib.o
obj-y += $(LUA_FOLDER)/ltablib.o
obj-y += $(LUA_FOLDER)/lstrlib.o
obj-y += $(LUA_FOLDER)/loadlib.o
obj-y += $(LUA_FOLDER)/linit.o

obj-y += lua_cmd.o

#include path
inc-y += $(LUA_FOLDER)/
