obj-$(CONFIG_TASK_APTC131) += c131_dlg.o
obj-$(CONFIG_TASK_APTC131) += c131_relay.o
obj-$(CONFIG_TASK_APTC131) += c131_misc.o
obj-$(CONFIG_TASK_APTC131) += c131_cmd.o
obj-$(CONFIG_TASK_APTC131) += c131_diag.o
obj-$(CONFIG_TASK_APTC131) += c131_can.o
